# Generated by Django 6.0.6 on 2026-08-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_about_contactinfo_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='completed_projects',
        ),
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='about',
            name='happy_clients',
        ),
        migrations.AddField(
            model_name='about',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='certificates',
            field=models.CharField(default='0+', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='experience',
            field=models.CharField(default='0+', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='projects',
            field=models.CharField(default='0+', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='technologies',
            field=models.CharField(default='0+', max_length=50),
        ),
    ]
