# Generated by Django 6.0.6 on 2026-08-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_about_completed_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(default='Technical Skills', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(default='Advanced', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(default=90),
        ),
    ]
