# Generated by Django 6.0.6 on 2026-08-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_demo_link_alter_project_github_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_link',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='live_url',
        ),
    ]
