# Generated by Django 6.0.6 on 2026-08-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_demo_link_project_github_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='subtitle',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github_url',
            new_name='demo_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='live_url',
            new_name='github_link',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='resume_url',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='title',
        ),
        migrations.AddField(
            model_name='hero',
            name='greeting',
            field=models.CharField(default="👋 Hello..., I'm", max_length=255),
        ),
        migrations.AddField(
            model_name='hero',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='resumeUrl',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
