# Generated by Django 6.0.6 on 2026-08-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_subtitle_hero_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experiences/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
