# Generated by Django 6.0.6 on 2026-08-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_experience_image_experience_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
